"""End-to-end workflow tests.

Drives Stages 1 → 5 (synthetic data → calibration → pricing) and
verifies four *non-tautological* invariants that hold for any
sensible quant library:

1. **Round-trip implied-vol / pricer consistency** — price a BS
   option, invert with Newton, recover the original vol.  Tests
   ``black_scholes_price`` *and* ``black_scholes_implied_vol`` in a
   way that the failure of either is informative.
2. **Engine cross-consistency** — analytic BS vs Monte Carlo BS on
   the *same* synthetic snapshot agree to within 3× the MC standard
   error.  No tautology because the two engines share no code path
   beyond the model definition.
3. **Autodiff Greeks vs central finite differences** — same pricer,
   two independent gradient methods, must agree.
4. **Curve self-consistency** — synthesised NSS truth curve reprices
   its own zero rates correctly through the public ``zero_rate``
   helper, and is interpolated consistently between pillars.

These do *not* check that "calibrate X on data generated by X recovers
X's parameters" — that is the tautology trap.
"""

from __future__ import annotations

import jax
import jax.numpy as jnp
import pytest

from valax.curves.discount import zero_rate
from valax.greeks.autodiff import greeks as ad_greeks
from valax.instruments.options import EuropeanOption
from valax.market.synthetic import (
    SyntheticMarketConfig,
    flat_discount_curve,
    sample_market_with_correlation,
    sample_nss_curve,
)
from valax.models.multi_asset import MultiAssetGBMModel
from valax.pricing.analytic.black_scholes import (
    black_scholes_implied_vol,
    black_scholes_price,
)
from valax.pricing.mc.multi_asset_paths import generate_correlated_gbm_paths


pytestmark = pytest.mark.detects


# ── 1. Round-trip pricer × implied-vol solver ─────────────────────


class TestPricerImpliedVolRoundTrip:
    def test_recovered_vol_matches_input(self, seed_registry):
        spot = jnp.array(105.0)
        strike = jnp.array(100.0)
        expiry = jnp.array(0.75)
        rate = jnp.array(0.04)
        dividend = jnp.array(0.01)
        vol_true = jnp.array(0.27)
        opt = EuropeanOption(strike=strike, expiry=expiry, is_call=True)

        price = black_scholes_price(opt, spot, vol_true, rate, dividend)
        vol_implied = black_scholes_implied_vol(
            opt, spot, rate, dividend, price, n_iterations=40,
        )
        assert float(vol_implied) == pytest.approx(float(vol_true), abs=1e-6)


# ── 2. Analytic vs Monte Carlo cross-check ────────────────────────


class TestEngineCrossConsistency:
    """Compare closed-form BS to a single-asset MC price.

    We use the multi-asset GBM path generator with n_assets=1 so the
    test exercises the production MC path; the analytic price is the
    standalone closed form.  Tolerance is 3× the MC stderr.
    """

    def test_call_price_matches_mc(self, seed_registry):
        spot = 100.0
        strike = 100.0
        vol = 0.20
        rate = 0.03
        dividend = 0.01
        T = 1.0

        # --- analytic
        opt = EuropeanOption(
            strike=jnp.array(strike),
            expiry=jnp.array(T),
            is_call=True,
        )
        analytic = float(
            black_scholes_price(
                opt,
                jnp.array(spot), jnp.array(vol),
                jnp.array(rate), jnp.array(dividend),
            )
        )

        # --- MC via the production multi-asset path generator
        model = MultiAssetGBMModel(
            vols=jnp.array([vol]),
            rate=jnp.array(rate),
            dividends=jnp.array([dividend]),
            correlation=jnp.eye(1),
        )
        n_paths = 200_000
        key = seed_registry.key("synthetic.test.cross_engine_mc")
        paths = generate_correlated_gbm_paths(
            model=model,
            spots=jnp.array([spot]),
            T=T,
            n_steps=1,
            n_paths=n_paths,
            key=key,
        )
        terminal = paths[:, -1, 0]
        payoffs = jnp.maximum(terminal - strike, 0.0)
        discount = float(jnp.exp(-rate * T))
        mc_mean = float(jnp.mean(payoffs)) * discount
        mc_stderr = float(jnp.std(payoffs)) / float(jnp.sqrt(n_paths)) * discount

        diff = abs(mc_mean - analytic)
        assert diff < 3.0 * mc_stderr, (
            f"analytic={analytic:.6f}, mc={mc_mean:.6f} ± "
            f"{mc_stderr:.6f}, diff={diff:.6f}"
        )


# ── 3. Autodiff vs finite-difference Greeks ───────────────────────


class TestAutodiffVsFD:
    """Compare ``valax.greeks.autodiff.greeks`` to central finite
    differences for a BS call.  Decouples 'we computed a Greek' from
    'we computed the right Greek'."""

    def test_delta_vega_rho_match_fd(self):
        spot = 100.0
        vol = 0.25
        rate = 0.04
        dividend = 0.01
        opt = EuropeanOption(
            strike=jnp.array(100.0),
            expiry=jnp.array(1.0),
            is_call=True,
        )

        g = ad_greeks(
            black_scholes_price, opt,
            jnp.array(spot), jnp.array(vol),
            jnp.array(rate), jnp.array(dividend),
        )

        def p(s, v, r, q):
            return float(
                black_scholes_price(
                    opt, jnp.array(s), jnp.array(v),
                    jnp.array(r), jnp.array(q),
                )
            )

        h_s, h_v, h_r = 1e-3, 1e-4, 1e-5
        delta_fd = (p(spot + h_s, vol, rate, dividend)
                    - p(spot - h_s, vol, rate, dividend)) / (2 * h_s)
        vega_fd = (p(spot, vol + h_v, rate, dividend)
                   - p(spot, vol - h_v, rate, dividend)) / (2 * h_v)
        rho_fd = (p(spot, vol, rate + h_r, dividend)
                  - p(spot, vol, rate - h_r, dividend)) / (2 * h_r)

        assert float(g["delta"]) == pytest.approx(delta_fd, rel=1e-4)
        assert float(g["vega"])  == pytest.approx(vega_fd, rel=1e-4)
        assert float(g["rho"])   == pytest.approx(rho_fd, rel=1e-3)


# ── 4. Curve self-consistency ─────────────────────────────────────


class TestCurveSelfConsistency:
    """Synthesised NSS curve must reprice its own pillar zero rates."""

    def test_pillar_dfs_reproducible_via_call(
        self, seed_registry, default_synth_cfg
    ):
        c = sample_nss_curve(seed_registry, default_synth_cfg)
        # Querying the curve at its own pillars should return the
        # stored DFs.
        dfs_at_pillars = c(c.pillar_dates)
        assert jnp.allclose(dfs_at_pillars, c.discount_factors)

    def test_zero_rate_invertible(
        self, seed_registry, default_synth_cfg
    ):
        c = sample_nss_curve(seed_registry, default_synth_cfg)
        # Pick the 5Y pillar (index 6 in default config) and verify
        # that DF(t) == exp(-r(t) * tau).
        idx = 6
        from valax.dates.daycounts import year_fraction
        r = zero_rate(c, c.pillar_dates[idx])
        tau = year_fraction(
            c.reference_date, c.pillar_dates[idx], c.day_count
        )
        df_via_rate = float(jnp.exp(-r * tau))
        df_stored = float(c.discount_factors[idx])
        assert df_via_rate == pytest.approx(df_stored, rel=1e-10)

    def test_flat_curve_reproduces_input_rate(self):
        from valax.dates.daycounts import ymd_to_ordinal

        ref = ymd_to_ordinal(2026, 1, 1)
        c = flat_discount_curve(rate=0.04, reference_date=ref)
        # Mid-tenor query: 5y
        mid_date = ref + 365 * 5
        r = float(zero_rate(c, mid_date))
        assert r == pytest.approx(0.04, abs=1e-10)
