"""Closed-loop calibration tests on synthetic data.

These tests promote the end-to-end workflow shown in
``examples/08_end_to_end_workflow.py`` into automated assertions.
They are **non-tautological**: rather than checking that calibrating
a model on data generated by that same model recovers the original
parameters (which would mostly verify the optimiser), they check
that the calibrator's residual lives at the observation-noise floor.

Test patterns
-------------
1. **SABR smile-residual** — synthesise a noisy SABR smile from a
   ground-truth :class:`SABRModel`, run :func:`calibrate_sabr`, assert
   the fitted-smile RMSE is within a multiplicative slack of the
   injected noise RMSE.  A failure means either the calibrator's
   convergence degraded or :func:`sabr_implied_vol` drifted.

2. **Bootstrap non-self roundtrip** — sample an NSS truth curve, read
   par-deposit-equivalent rates at a set of tenors *different from*
   the NSS pillars, bootstrap a new :class:`DiscountCurve` from those
   quotes, and assert it reproduces the truth's zero rates at
   *off-pillar* dates within an interpolation tolerance.  Because the
   bootstrap and the truth have different pillar grids, this is a
   real test of interpolation quality, not a self-roundtrip.

Heston note
-----------
Heston calibration via Monte Carlo is too slow for unit-test latency
(each Levenberg-Marquardt step requires many MC reprices, each
spawning thousands of paths).  We keep a placeholder
:class:`TestHestonMCCalibration` skipped with the reason logged, and
revisit when a semi-analytic Heston pricer (Carr-Madan or Lewis FFT)
lands.
"""

from __future__ import annotations

import jax
import jax.numpy as jnp
import pytest

from valax.calibration import calibrate_sabr
from valax.curves.bootstrap import bootstrap_sequential
from valax.curves.discount import zero_rate
from valax.curves.instruments import DepositRate
from valax.dates.daycounts import year_fraction
from valax.market.synthetic import (
    sample_nss_curve,
    sample_sabr_params,
    synthesize_sabr_smile,
)
from valax.pricing.analytic.sabr import sabr_implied_vol


pytestmark = pytest.mark.detects


# ── 1. SABR smile-residual ────────────────────────────────────────


class TestSABRSmileResidual:
    """`calibrate_sabr` must fit a noisy smile to within the noise floor."""

    # Strike grid and tenor are deterministic so the assertion is
    # reproducible.  Forward = 100, expiry = 1Y, 13 strikes around ATM.
    FORWARD = jnp.array(100.0)
    EXPIRY = jnp.array(1.0)
    STRIKES = jnp.linspace(70.0, 130.0, 13)
    NOISE_BP = 10.0

    # Slack factor: the fit RMSE may exceed the noise RMSE by at most
    # this multiple.  The factor accounts for finite-strike-grid
    # estimation variance and the asymmetry of fit-vs-data noise.
    SLACK = 1.5

    def test_sabr_fit_within_noise_floor(self, seed_registry, default_synth_cfg):
        sabr_truth = sample_sabr_params(seed_registry, default_synth_cfg)

        smile_clean = synthesize_sabr_smile(
            seed_registry, sabr_truth, self.FORWARD, self.EXPIRY,
            self.STRIKES, vol_bp_noise=0.0,
        )
        smile_noisy = synthesize_sabr_smile(
            seed_registry, sabr_truth, self.FORWARD, self.EXPIRY,
            self.STRIKES, vol_bp_noise=self.NOISE_BP,
        )
        # Empirical noise RMSE on this draw.
        noise_rms = float(
            jnp.sqrt(jnp.mean((smile_noisy - smile_clean) ** 2))
        )

        sabr_fit, sol = calibrate_sabr(
            strikes=self.STRIKES,
            market_vols=smile_noisy,
            forward=self.FORWARD,
            expiry=self.EXPIRY,
            fixed_beta=sabr_truth.beta,
        )

        smile_fit = jax.vmap(
            lambda K: sabr_implied_vol(sabr_fit, self.FORWARD, K, self.EXPIRY)
        )(self.STRIKES)
        fit_rms = float(jnp.sqrt(jnp.mean((smile_fit - smile_noisy) ** 2)))

        assert fit_rms <= self.SLACK * noise_rms, (
            f"SABR fit RMSE {fit_rms*1e4:.2f} bp exceeds "
            f"{self.SLACK:.1f}× noise RMSE {noise_rms*1e4:.2f} bp."
        )

    def test_noiseless_fit_is_near_zero(self, seed_registry, default_synth_cfg):
        """With zero noise, the fit should be near machine precision."""
        sabr_truth = sample_sabr_params(seed_registry, default_synth_cfg)
        smile = synthesize_sabr_smile(
            seed_registry, sabr_truth, self.FORWARD, self.EXPIRY,
            self.STRIKES, vol_bp_noise=0.0,
        )
        sabr_fit, _ = calibrate_sabr(
            strikes=self.STRIKES,
            market_vols=smile,
            forward=self.FORWARD,
            expiry=self.EXPIRY,
            fixed_beta=sabr_truth.beta,
        )
        smile_fit = jax.vmap(
            lambda K: sabr_implied_vol(sabr_fit, self.FORWARD, K, self.EXPIRY)
        )(self.STRIKES)
        fit_rms = float(jnp.sqrt(jnp.mean((smile_fit - smile) ** 2)))
        # 0.5 bp is generous slack for a Levenberg-Marquardt fit on
        # clean data — anything larger means the calibrator's
        # convergence has degraded.
        assert fit_rms * 1e4 < 0.5, (
            f"Noiseless SABR fit RMSE = {fit_rms*1e4:.4f} bp; "
            "expected near machine precision."
        )


# ── 2. Bootstrap non-self roundtrip ───────────────────────────────


class TestBootstrapRoundTrip:
    """NSS truth → deposit quotes at *non-NSS* tenors → bootstrap →
    check off-pillar zero-rate recovery within interpolation tolerance.

    Why this is non-tautological:
        The NSS truth curve has 12 pillars on the standard money-market
        + swap grid.  We synthesise deposit quotes at four custom
        tenors (4M, 18M, 4Y, 8Y) that *avoid* the NSS pillar dates,
        so the bootstrap's interpolation must reconstruct the truth
        from a strictly coarser, mis-aligned grid.  Comparing zero
        rates at yet a third set of dates (1Y, 3Y, 6Y) measures real
        interpolation error, not a self-roundtrip.
    """

    # Tenors at which we synthesise deposit quotes (these become
    # the bootstrap pillars).  Deliberately offset from the NSS
    # pillars (which sit at 1M, 3M, 6M, 1Y, 2Y, 3Y, 5Y, 7Y, ...).
    QUOTE_TENORS_DAYS = (120, 540, 1460, 2920)   # ~4M, 18M, 4Y, 8Y

    # Tenors at which we compare zero rates (none coincides with
    # either grid above).
    CHECK_TENORS_DAYS = (240, 900, 1825)         # ~8M, 30M, 5Y

    # Interpolation tolerance.  Log-linear DF interpolation on an NSS
    # curve produces O(10 bp) zero-rate error at the worst between-pillar
    # midpoints; 25 bp is comfortable headroom.
    ZERO_RATE_TOLERANCE = 25e-4

    def _deposit_par_rate(
        self,
        truth_curve,
        end_date,
    ) -> float:
        """Simply-compounded par-deposit rate implied by the truth curve."""
        ref = truth_curve.reference_date
        tau = year_fraction(ref, end_date, truth_curve.day_count)
        df = truth_curve(end_date)
        # rate = (DF(start) / DF(end) - 1) / tau  with DF(start)=1.
        return float((1.0 / df - 1.0) / tau)

    def test_offpillar_zero_rates_match(
        self, seed_registry, default_synth_cfg
    ):
        truth = sample_nss_curve(seed_registry, default_synth_cfg)
        ref = truth.reference_date

        # Build deposit quotes at the chosen non-NSS tenors.
        quotes = []
        for d_days in self.QUOTE_TENORS_DAYS:
            end = jnp.int32(int(ref) + d_days)
            rate = self._deposit_par_rate(truth, end)
            quotes.append(
                DepositRate(
                    start_date=ref,
                    end_date=end,
                    rate=jnp.array(rate),
                    day_count=truth.day_count,
                )
            )

        fitted = bootstrap_sequential(
            ref, quotes, day_count=truth.day_count
        )

        # (a) Sanity: at the bootstrap pillars, par rates match exactly.
        for q in quotes:
            df_truth = float(truth(q.end_date))
            df_fit = float(fitted(q.end_date))
            assert df_fit == pytest.approx(df_truth, abs=1e-10), (
                f"Bootstrap should reproduce its own quotes at pillars."
            )

        # (b) Real test: zero rates at off-pillar dates match truth
        # within the interpolation tolerance.
        max_err = 0.0
        for d_days in self.CHECK_TENORS_DAYS:
            date = jnp.int32(int(ref) + d_days)
            r_truth = float(zero_rate(truth, date))
            r_fit = float(zero_rate(fitted, date))
            max_err = max(max_err, abs(r_fit - r_truth))

        assert max_err <= self.ZERO_RATE_TOLERANCE, (
            f"Off-pillar zero-rate mismatch {max_err*1e4:.1f} bp "
            f"exceeds tolerance {self.ZERO_RATE_TOLERANCE*1e4:.1f} bp."
        )

    def test_flat_truth_recovers_exactly(self, seed_registry):
        """When the truth curve is itself flat, the bootstrap must
        recover it exactly at every date (interpolation error = 0).

        Provides a stronger upper bound than the NSS test above and
        catches any drift in the deposit-DF formula or the day-count
        wiring."""
        from valax.dates.daycounts import ymd_to_ordinal
        from valax.market.synthetic import flat_discount_curve

        ref = ymd_to_ordinal(2026, 1, 1)
        truth = flat_discount_curve(rate=0.035, reference_date=ref)

        quotes = []
        for d_days in self.QUOTE_TENORS_DAYS:
            end = jnp.int32(int(ref) + d_days)
            rate = self._deposit_par_rate(truth, end)
            quotes.append(
                DepositRate(
                    start_date=ref, end_date=end, rate=jnp.array(rate),
                    day_count=truth.day_count,
                )
            )
        fitted = bootstrap_sequential(
            ref, quotes, day_count=truth.day_count
        )

        # On a flat truth, the bootstrap interpolates between exact
        # pillar matches, so the only error is whatever log-linear
        # interpolation in DF space introduces.  For an exponential
        # truth, that error is also zero (log DF is linear in time).
        for d_days in self.CHECK_TENORS_DAYS:
            date = jnp.int32(int(ref) + d_days)
            r_truth = float(zero_rate(truth, date))
            r_fit = float(zero_rate(fitted, date))
            assert r_fit == pytest.approx(r_truth, abs=1e-8), (
                f"Flat-truth bootstrap should be exact; got "
                f"{(r_fit - r_truth)*1e4:.4f} bp at day {d_days}."
            )


# ── 3. Heston (deferred) ──────────────────────────────────────────


class TestHestonMCCalibration:
    @pytest.mark.skip(
        reason=(
            "Heston calibration via Monte Carlo is too slow for unit "
            "tests (each LM step requires N MC reprices).  Re-enable "
            "once a semi-analytic Heston pricer (Carr-Madan or "
            "Lewis FFT) lands in valax/pricing/analytic/."
        )
    )
    def test_heston_mc_fit_within_noise_floor(self):
        pass
